import '../blocks/block-button/ripple/ripple.js'
import '../blocks/block-svg-percentages/svg-percentages.js'
import '../blocks/block-svg-chart/svg-chart.js'
import '../blocks/block-slider/slider.js'
import '../blocks/block-stages/stages.js'